spec:
  authentication:
  - name: oidc
    oidc:
      clientID: ${client_id}
      cloudConsoleRedirectURI: https://console.cloud.google.com/kubernetes/oidc
      extraParams: prompt=consent
      issuerURI: ${issuer}
      kubectlRedirectURI: http://localhost:8000
      scopes: openid,profile,email,groups,offline_access
      userClaim: ${user_claim}
      groupsClaim: ${groups_claim}
      userPrefix: "${prefix}"
      groupPrefix: "${prefix}"
